- name: Create Woodpecker directory
  ansible.builtin.file:
    path: /opt/woodpecker
    state: directory
    mode: 0700
  tags:
    - woodpecker

- name: Install Woodpecker server
  community.docker.docker_compose:
    project_name: woodpecker_server
    pull: true
    definition:
      version: "3"
      services:
        woodpecker-server:
          image: woodpeckerci/woodpecker-server:{{ woodpecker_version }}
          restart: always
          volumes:
            - /opt/woodpecker:/var/lib/woodpecker/
          networks:
            - web
            - default
          environment:
            - WOODPECKER_OPEN=true
            - WOODPECKER_HOST={{ woodpecker_host }}
            - WOODPECKER_ORGS={{ woodpecker_orgs }}
            - WOODPECKER_ADMIN={{ woodpecker_admins }}
            - WOODPECKER_GITHUB=true
            - WOODPECKER_GITHUB_CLIENT={{ woodpecker_github_client }}
            - WOODPECKER_GITHUB_SECRET={{ woodpecker_github_secret }}
            - WOODPECKER_AGENT_SECRET={{ woodpecker_agent_secret }}
            - WOODPECKER_GITHUB_MERGE_REF=false
        logs-migrator:
          image: codeberg.org/6543/woodpecker_logs_migrator
          volumes:
            - /opt/woodpecker:/var/lib/woodpecker/
          environment:
            - WOODPECKER_DATABASE_DRIVER=sqlite3
            - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
      networks:
        web:
          external:
            name: web
  tags:
    - woodpecker
    - woodpecker-server
